#------------------------------------------------------------------------------------------------ 15 COL - 5 ROW
#   | ESC |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |  9  |  0  |  ?  |  ¿  |SUPR |INSER|
#   | TAB |  Q  |  W  |  E  |  R  |  T  |  Y  |  U  |  I  |  O  |  P  | ´¨  | +*  |HOME |IMP P|
#   |MAYUS|  A  |  S  |  D  |  F  |  G  |  H  |  J  |  K  |  L  |  Ñ  |  {[ | }]  | END |REPAG|
#   |SHIFT| < > |  Z  |  X  |  C  |  V  |  B  |  N  |  M  |  ,  |  .  |  -  |SHIFT| UP  |AVPAG|
#   |CNTRL| WIN | ALT | BACKSPACE |   SPACE   |   ENTER   |ALTGR|  FN |CNTRL|LEFT |DOWN |RIGHT|